baseURL = 'https://sahifaty.netlify.app/'
languageCode = 'ar-eg'
title = 'sahifaty'
pluralizeListTitles =   false
# theme = 'basic'
[params]
    title_header = "صحيفتي"
    homepage_name = "الصفحة الرئيسية"
    posts_name = "منشورات"
    about_name = "حولنا"
    others_name = "أخرى"
    copy_rights = "حقوق النشر &copy;محفوظة"
    aside_panel_name = "أخرى"
    author = "Mahir Mo"
